package org.gevernova.JavaEightFeatures.ProductSalesAnalysis;

/**
 * Represents aggregated sales data for a product.
 * Stores product ID and total revenue (tr).
 */
public class ProductSales {

    // Unique identifier of the product
    int productId;

    // Total revenue generated by the product
    int tr;

    /**
     * Constructor to initialize product sales data.
     *
     * @param productId Product ID
     * @param tr        Total revenue
     */
    public ProductSales(int productId, int tr) {
        this.productId = productId;
        this.tr = tr;
    }

    /**
     * @return Product ID
     */
    public int getProductId() {
        return productId;
    }

    /**
     * @return Total revenue
     */
    public int getTr() {
        return tr;
    }

    /**
     * Returns a readable string representation
     * of the ProductSales object.
     *
     * @return String describing product sales
     */
    @Override
    public String toString() {
        return "ProductSales{" +
                "productId=" + productId +
                ", tr=" + tr +
                '}';
    }
}
